title: Ting Chih Lin
email: tc.lin@berkeley.edu
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
permalink: ':title/'
baseurl: "/tingchihlin" # the subpath of your site, e.g. /blog
url: "http://rexlintc.github.io" # the base hostname & protocol for your site, e.g. http://example.com

# Author settings
author: Ting Chih Lin # add your name
author-pic: adam-face.jpg
about-author: My name is Ting Chih Lin.

# Contact links
email: tc.lin@berkeley.edu # Add your Email address
phone: 510-833-8803 # Add your Phone number
website: rexlintc.github.io # Add your website, do not add http://
linkedin: # Add your Linkedin handle
github: rexlintc # Add your Github handle
twitter: '@rexlintc' # Add your Twitter handle
facebook: # Add your Facebook handle
instagram: # Add your Instagram handle
pinterest: # Add your Pinterest handle

# Newsletter
mailchimp: # Add your MailChimp form identifier.

# Disqus
discus_identifier: # Add your discus identifier

# Tracker
analytics: # Google Analytics

# Paginate
paginate: 6
paginate_path: /page:num/

# Build settings
markdown: kramdown
gems:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-sitemap

include: [_pages]
exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
